import 'package:flutter/material.dart';

/// Catalogue of every Wajiha game - powers cross-promotion in all games.
class GameInfo {
  final String slug;
  final String name;
  final String tagline;
  final String emoji;
  final Color color1;
  final Color color2;
  const GameInfo({required this.slug, required this.name, required this.tagline, required this.emoji, required this.color1, required this.color2});
}

const List<GameInfo> kAllGames = [
  GameInfo(slug: 'ludo', name: 'Ludo', tagline: 'Classic 2-4 player board race game with dice, stars and safe zones', emoji: '🎲', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'carromclash', name: 'Carrom Clash', tagline: 'Flick discs into pockets in this 2-player carrom board game', emoji: '🥏', color1: Color(0xFF4ECDC4), color2: Color(0xFF1A936F)),
  GameInfo(slug: 'chess', name: 'Chess', tagline: 'Full classic chess with smart bot, 2-player local and puzzles', emoji: '♟️', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'checkers', name: 'Checkers', tagline: 'Classic draughts with forced captures, 2-player and vs bot', emoji: '⚫', color1: Color(0xFF7BF1A8), color2: Color(0xFF2E9E6B)),
  GameInfo(slug: 'tictactoe', name: 'Tic Tac Toe', tagline: 'The timeless 3x3 duel with smart AI and party modes', emoji: '❌', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'backgammon', name: 'Backgammon', tagline: 'Race your checkers home with dice strategy and doubling cube', emoji: '🎯', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'snakesandladders', name: 'Snakes and Ladders', tagline: 'Climb ladders, dodge snakes in this 2-4 player family classic', emoji: '🐍', color1: Color(0xFF4ECDC4), color2: Color(0xFF1A936F)),
  GameInfo(slug: 'mancala', name: 'Mancala', tagline: 'Ancient pit-and-seed strategy game, 2 players or vs clever bot', emoji: '🫘', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'flipdiscs', name: 'Flip Discs', tagline: 'Outflank and flip your rival\'s discs on the 8x8 board', emoji: '🔄', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'dominoes', name: 'Dominoes', tagline: 'Tile-matching classic with draw and block modes for 2-4 players', emoji: '🀄', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'fourinarow', name: 'Four in a Row', tagline: 'Drop discs and connect four before your opponent does', emoji: '🔴', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'go', name: 'Go', tagline: 'The ancient game of territory on 9x9, 13x13 and 19x19 boards', emoji: '⚫', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'chinesecheckers', name: 'Chinese Checkers', tagline: 'Hop your marbles across the star in 2-6 player fun', emoji: '🔮', color1: Color(0xFFFF6B6B), color2: Color(0xFFFF4D6D)),
  GameInfo(slug: 'tilesolitaire', name: 'Tile Solitaire', tagline: 'Match pairs of tiles to clear the beautiful layouts', emoji: '🃏', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'shogi', name: 'Shogi', tagline: 'Japanese chess with piece drops, vs bot or a friend', emoji: '♞', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'gomoku', name: 'Gomoku', tagline: 'Five in a row wins in this deep yet simple duel', emoji: '⭕', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'reversirush', name: 'Reversi Rush', tagline: 'Speed flip-disc battles against the clock and rivals', emoji: '⏱️', color1: Color(0xFF7BF1A8), color2: Color(0xFF2E9E6B)),
  GameInfo(slug: 'dotsandboxes', name: 'Dots and Boxes', tagline: 'Claim boxes and outsmart your opponent, 2-4 players', emoji: '📦', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'ninemensmorris', name: 'Nine Mens Morris', tagline: 'Mill, move and capture in this ancient strategy duel', emoji: '🏰', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'hex', name: 'Hex', tagline: 'Connect your sides in the purest connection game ever made', emoji: '⬡', color1: Color(0xFFFFC531), color2: Color(0xFFFF9E4F)),
  GameInfo(slug: 'jewelmatch', name: 'Jewel Match', tagline: 'Swap and blast sparkling gems in endless match-3 levels', emoji: '💎', color1: Color(0xFFFF6B6B), color2: Color(0xFFFF4D6D)),
  GameInfo(slug: 'sudoku', name: 'Sudoku', tagline: 'Classic number logic with 5 difficulties and daily puzzles', emoji: '🔢', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'merge2048', name: 'Merge 2048', tagline: 'Slide and merge numbers to reach the legendary 2048 tile', emoji: '2️⃣', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'watersort', name: 'Water Sort', tagline: 'Pour colorful liquids and sort every tube perfectly', emoji: '🧪', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'blockfill', name: 'Block Fill', tagline: 'Fit every block piece into the grid in this cozy puzzle', emoji: '🧱', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'slidingpuzzle', name: 'Sliding Puzzle', tagline: 'Slide the tiles back into place, from 3x3 to 6x6', emoji: '🧩', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'nonogram', name: 'Nonogram', tagline: 'Paint pixel pictures with clever row and column logic', emoji: '🎨', color1: Color(0xFFFF6B6B), color2: Color(0xFFFF4D6D)),
  GameInfo(slug: 'kakuro', name: 'Kakuro', tagline: 'Cross-sums number puzzle for true logic lovers', emoji: '➕', color1: Color(0xFF4CC9F0), color2: Color(0xFF4361EE)),
  GameInfo(slug: 'jigsaw', name: 'Jigsaw', tagline: 'Relaxing jigsaw puzzles with gorgeous generated pictures', emoji: '🧩', color1: Color(0xFFFF9E4F), color2: Color(0xFFF59E0B)),
  GameInfo(slug: 'unblockcar', name: 'Unblock Car', tagline: 'Slide the traffic and free the red car from the jam', emoji: '🚗', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'pipeconnect', name: 'Pipe Connect', tagline: 'Twist and connect every pipe to light up the board', emoji: '🔧', color1: Color(0xFFFF6B6B), color2: Color(0xFFFF4D6D)),
  GameInfo(slug: 'minefinder', name: 'Mine Finder', tagline: 'Flag the mines and clear the field without a boom', emoji: '💣', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'flowlines', name: 'Flow Lines', tagline: 'Connect matching colors without crossing the flows', emoji: '🌊', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'wordsearch', name: 'Word Search', tagline: 'Find hidden words in themed letter grids', emoji: '🔍', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'crossword', name: 'Crossword', tagline: 'Classic crosswords with hints and smart checking', emoji: '📝', color1: Color(0xFFFFC531), color2: Color(0xFFFF9E4F)),
  GameInfo(slug: 'wordlink', name: 'Word Link', tagline: 'Connect letters to build words in hundreds of levels', emoji: '🔗', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'solitaire', name: 'Solitaire', tagline: 'The timeless Klondike card classic, smooth and relaxing', emoji: '🃏', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'spidersolitaire', name: 'Spider Solitaire', tagline: 'Eight-suit-free spider with 1, 2 and 4 suit modes', emoji: '🕷️', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'hearts', name: 'Hearts', tagline: 'Avoid the hearts and the queen of spades to win', emoji: '♥️', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'spades', name: 'Spades', tagline: 'Bid bold and take tricks in this 4-player card classic', emoji: '♠️', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'rummy', name: 'Rummy', tagline: 'Meld sets and runs before your rivals do', emoji: '🎴', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'blackjack', name: 'Blackjack', tagline: 'Beat the dealer to 21 in this casino classic', emoji: '🂡', color1: Color(0xFF4CC9F0), color2: Color(0xFF4361EE)),
  GameInfo(slug: 'lonestarpoker', name: 'Lone Star Poker', tagline: 'Solo Texas-style poker against crafty bot rivals', emoji: '♠️', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'wordguess', name: 'Word Guess', tagline: 'Guess the hidden word in six tries, daily puzzle included', emoji: '💬', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'anagrams', name: 'Anagrams', tagline: 'Unscramble letters against the clock in word battles', emoji: '🔤', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'hangman', name: 'Hangman', tagline: 'Guess the word before the drawing is complete', emoji: '🪢', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'brickcrusher', name: 'Brick Crusher', tagline: 'Bounce the ball and smash every brick with power-ups', emoji: '🧱', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'bubblepop', name: 'Bubble Pop', tagline: 'Aim, match and pop bubbles in 200+ fizzy levels', emoji: '🫧', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'snake', name: 'Snake', tagline: 'Eat, grow and survive in the arcade legend, remixed', emoji: '🐍', color1: Color(0xFF4CC9F0), color2: Color(0xFF4361EE)),
  GameInfo(slug: 'mazemuncher', name: 'Maze Muncher', tagline: 'Gobble every pellet and outsmart the ghosts in the maze', emoji: '👻', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'starblaster', name: 'Star Blaster', tagline: 'Pilot your ship through waves of alien invaders', emoji: '🚀', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'paddleclash', name: 'Paddle Clash', tagline: 'The original arcade duel, now with spin and power shots', emoji: '🏓', color1: Color(0xFF4CC9F0), color2: Color(0xFF4361EE)),
  GameInfo(slug: 'blockdrop', name: 'Block Drop', tagline: 'Stack falling blocks and clear lines in the endless puzzler', emoji: '🟧', color1: Color(0xFF4CC9F0), color2: Color(0xFF4361EE)),
  GameInfo(slug: 'rockblaster', name: 'Rock Blaster', tagline: 'Blast asteroids and dodge the debris field', emoji: '☄️', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'pinball', name: 'Pinball', tagline: 'Flip, bump and chase the high score on neon tables', emoji: '🎰', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'roadhopper', name: 'Road Hopper', tagline: 'Hop across roads and rivers without getting squashed', emoji: '🐸', color1: Color(0xFFFF6B6B), color2: Color(0xFFFF4D6D)),
  GameInfo(slug: 'slicefrenzy', name: 'Slice Frenzy', tagline: 'Slice flying fruit with combo blades and slow-mo', emoji: '🍉', color1: Color(0xFFFF6B6B), color2: Color(0xFFFF4D6D)),
  GameInfo(slug: 'bladetoss', name: 'Blade Toss', tagline: 'Stick every blade into the spinning target', emoji: '🔪', color1: Color(0xFFFFC531), color2: Color(0xFFFF9E4F)),
  GameInfo(slug: 'spiraldrop', name: 'Spiral Drop', tagline: 'Bounce down the helix tower, avoid the red zones', emoji: '🌀', color1: Color(0xFFFF6B6B), color2: Color(0xFFFF4D6D)),
  GameInfo(slug: 'flapdash', name: 'Flap Dash', tagline: 'Tap to fly through the pipes, simple and addictive', emoji: '🐤', color1: Color(0xFFFF9E4F), color2: Color(0xFFF59E0B)),
  GameInfo(slug: 'dashrunner', name: 'Dash Runner', tagline: 'Jump, slide and dash through an endless neon world', emoji: '🏃', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'huehop', name: 'Hue Hop', tagline: 'Bounce through color gates that match your ball', emoji: '🎨', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'towerstack', name: 'Tower Stack', tagline: 'Stack moving blocks into the tallest tower', emoji: '🏗️', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'tapdash', name: 'Tap Dash', tagline: 'One-tap rhythm dashing through tricky levels', emoji: '👆', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'circlerush', name: 'Circle Rush', tagline: 'Spin, dodge and survive the rushing circle arena', emoji: '⭕', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'zigzagdash', name: 'Zigzag Dash', tagline: 'Zig and zag without falling off the endless path', emoji: '⚡', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'memorymatch', name: 'Memory Match', tagline: 'Flip cards and match every pair, solo or party mode', emoji: '🃏', color1: Color(0xFFFF9E4F), color2: Color(0xFFF59E0B)),
  GameInfo(slug: 'findthedifference', name: 'Find the Difference', tagline: 'Spot every difference in beautiful scenes', emoji: '👀', color1: Color(0xFF4CC9F0), color2: Color(0xFF4361EE)),
  GameInfo(slug: 'mathmaster', name: 'Math Master', tagline: 'Speed arithmetic battles that sharpen your brain', emoji: '➗', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'braingym', name: 'Brain Gym', tagline: 'Daily brain workouts across memory, logic and focus', emoji: '🧠', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'logicgrid', name: 'Logic Grid', tagline: 'Solve Einstein-style logic grid puzzles', emoji: '🧮', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'codebreaker', name: 'Code Breaker', tagline: 'Crack the secret color code in 10 tries or less', emoji: '🕵️', color1: Color(0xFF7BF1A8), color2: Color(0xFF2E9E6B)),
  GameInfo(slug: 'simon', name: 'Simon', tagline: 'Repeat the growing light and sound sequence', emoji: '🔔', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'twistycube', name: 'Twisty Cube', tagline: 'Twist the 3D cube back to solved, with solver hints', emoji: '🧊', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'hexasort', name: 'Hexa Sort', tagline: 'Sort colorful hex nuts onto matching bolts', emoji: '🔩', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'colorfill', name: 'Color Fill', tagline: 'Flood the board with one color in limited moves', emoji: '🪣', color1: Color(0xFF7BF1A8), color2: Color(0xFF2E9E6B)),
  GameInfo(slug: 'bowling', name: 'Bowling', tagline: 'Strike down pins in 10-frame bowling nights', emoji: '🎳', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'minigolf', name: 'Mini Golf', tagline: 'Putt through tricky courses under par', emoji: '⛳', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'pocketbilliards', name: 'Pocket Billiards', tagline: 'Pot every ball in smooth 8-ball pool matches', emoji: '🎱', color1: Color(0xFF7BF1A8), color2: Color(0xFF2E9E6B)),
  GameInfo(slug: 'hoopshoot', name: 'Hoop Shoot', tagline: 'Swish shot after shot in arcade basketball', emoji: '🏀', color1: Color(0xFF4ECDC4), color2: Color(0xFF1A936F)),
  GameInfo(slug: 'archery', name: 'Archery', tagline: 'Aim true and bullseye moving targets', emoji: '🏹', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'darts', name: 'Darts', tagline: 'Hit 501 exactly with precision dart throws', emoji: '🎯', color1: Color(0xFF7BF1A8), color2: Color(0xFF2E9E6B)),
  GameInfo(slug: 'flipbottle', name: 'Flip Bottle', tagline: 'Flip the bottle and land it upright, trick-shot style', emoji: '🍼', color1: Color(0xFFF72585), color2: Color(0xFF7209B7)),
  GameInfo(slug: 'paperflick', name: 'Paper Flick', tagline: 'Flick paper balls into the bin from anywhere', emoji: '🗑️', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'driftsling', name: 'Drift Sling', tagline: 'Sling around corners in drift racing duels', emoji: '🏎️', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'balanceit', name: 'Balance It', tagline: 'Stack and balance objects without toppling', emoji: '⚖️', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'pixelracer', name: 'Pixel Racer', tagline: 'Retro 2D racing with nitro and tight corners', emoji: '🏁', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'mountainrider', name: 'Mountain Rider', tagline: 'Climb crazy hills, flip and upgrade your ride', emoji: '🏔️', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'penaltykick', name: 'Penalty Kick', tagline: 'Score past the keeper in penalty shootouts', emoji: '⚽', color1: Color(0xFF38BDF8), color2: Color(0xFF0EA5E9)),
  GameInfo(slug: 'tennis', name: 'Tennis', tagline: 'Rally, smash and win on grass and clay courts', emoji: '🎾', color1: Color(0xFF4CC9F0), color2: Color(0xFF4361EE)),
  GameInfo(slug: 'airhockey', name: 'Air Hockey', tagline: 'Slide the puck past your rival in fast air hockey', emoji: '🏒', color1: Color(0xFFFF6B6B), color2: Color(0xFFFF4D6D)),
  GameInfo(slug: 'tabletennis', name: 'Table Tennis', tagline: 'Spin and smash in lightning table tennis rallies', emoji: '🏓', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'cricket', name: 'Cricket', tagline: 'Smash sixes and bowl yorkers in quick cricket clashes', emoji: '🏏', color1: Color(0xFFFF9E4F), color2: Color(0xFFF59E0B)),
  GameInfo(slug: 'homerun', name: 'Home Run', tagline: 'Time your swing and smash it out of the park', emoji: '⚾', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'snowslalom', name: 'Snow Slalom', tagline: 'Carve through slalom gates down the mountain', emoji: '⛷️', color1: Color(0xFFFF5DA2), color2: Color(0xFF7C5CFF)),
  GameInfo(slug: 'driftracer', name: 'Drift Racer', tagline: 'Drift through corners and own the leaderboard', emoji: '🏎️', color1: Color(0xFF00F5D4), color2: Color(0xFF7B2FF7)),
  GameInfo(slug: 'towerdefense', name: 'Tower Defense', tagline: 'Build towers and stop the endless enemy waves', emoji: '🗼', color1: Color(0xFF84CC16), color2: Color(0xFF15803D)),
  GameInfo(slug: 'idleclicker', name: 'Idle Clicker', tagline: 'Tap, upgrade and automate your gold empire', emoji: '👆', color1: Color(0xFF4CC9F0), color2: Color(0xFF4361EE)),
  GameInfo(slug: 'seabattle', name: 'Sea Battle', tagline: 'Sink the hidden fleet before yours goes down', emoji: '🚢', color1: Color(0xFFB967FF), color2: Color(0xFF5C2E9E)),
  GameInfo(slug: 'mergefarm', name: 'Merge Farm', tagline: 'Merge crops and animals to grow your dream farm', emoji: '🚜', color1: Color(0xFFFF9E4F), color2: Color(0xFFF59E0B)),
];
